btitle: "maximizer heavy ind."
author: "scottvr"
description: "wetware neuronal activations consolidated and temporally-ordered."
email: "scottvr at paperclipmaximizer"
#twitter_username: "twitteruser"
github_username: "scottvr"
linkedin_username: "scottvr"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

##

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
collections:
  posts:
    output          : true
  pages:
    output          : true
    
# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown            : GFM
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
